[build-system]
requires = [
  "setuptools>=61.0",
  "wheel",
  "cmake>=3.15",
  "pybind11>=2.11.1",
]
build-backend = "setuptools.build_meta"

[project]
name = "kimodo"
version = "1.0.0"
description = "Kimodo motion generation model"
readme = "README.md"
requires-python = ">=3.10,<3.14"
license = {text = "Apache-2.0"}
dependencies = [
  "hydra-core>=1.3",
  "omegaconf>=2.3",
  "numpy>=1.23",
  "scipy>=1.10",
  "torch",
  "transformers==5.1.0",
  "urllib3>=2.6.3",
  "boto3",
  "peft>=0.18",
  "einops>=0.7",
  "tqdm>=4.0",
  "packaging>=21.0",
  "pydantic>=2.0",
  "filelock>=3.20.3",
  "gradio>=6.8.0",
  "gradio_client>=1.0",
  "trimesh>=3.21.7",
  "scenepic>=1.1.0",
  "pillow>=9.0",
  "av>=16.1.0",
  "bvhio",
]

[project.optional-dependencies]
server = [
  "fastapi>=0.115",
  "uvicorn[standard]>=0.30",
]
demo = [
  "viser @ git+https://github.com/nv-tlabs/kimodo-viser.git",
]
soma = [
  "py-soma-x @ git+https://github.com/NVlabs/SOMA-X.git"
]
all = [
  "fastapi>=0.115",
  "uvicorn[standard]>=0.30",
  "viser @ git+https://github.com/nv-tlabs/kimodo-viser.git",
  "py-soma-x @ git+https://github.com/NVlabs/SOMA-X.git"
]

[dependency-groups]
dev = [
  "ruff",
  "pre-commit",
  "pytest",
]
docs = [
  "sphinx>=7.0,<9.0",
  "nvidia-sphinx-theme",
  "sphinx-copybutton",
  "myst-parser",
  "sphinx-design",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cu130", marker = "sys_platform == 'win32' or sys_platform == 'linux'" },
]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[project.scripts]
kimodo_gen = "kimodo.scripts.generate:main"
kimodo_demo = "kimodo.demo:main"
kimodo_textencoder = "kimodo.scripts.run_text_encoder_server:main"
kimodo_convert = "kimodo.scripts.motion_convert:main"

[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.setuptools.package-data]
kimodo = ["assets/**/*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
markers = [
  "server: server module tests",
  "runtime: real runtime or ModelRuntime tests",
  "inference: tests that perform real model inference",
  "slow: slow tests",
]
norecursedirs = [
  ".git",
  ".ruff_cache",
  ".uv-cache",
  ".venv",
  "outputs",
  "pytest-cache-files-*",
]

[tool.flake8]
max-line-length = 120

[tool.ruff]
extend-select = ["I001"]  # Enable import sorting
line-length = 120

[tool.ruff.lint.isort]
known-first-party = ["kimodo"]
known-third-party = ["torch", "numpy", "pytorch_lightning", "wandb", "tqdm"]
force-sort-within-sections = false
